Lesson 03 task
karamel29/go-courses pull request #3
Opened 2021-07-16 13:12 UTC by karamel29

2021-07-16 15:40 UTC, IgorZhadenovEpam commented on task003/main.go
> +}
There is a little problem with this code
"Implement reverse([]int64) []int64 function, that returns the **COPY** of the original slice in reverse order. "
But you reverse and return the original slice 
https://play.golang.org/p/e4pgoTKTPbz

2021-07-19 11:22 UTC, DzmitryYafremenka requested changes

2021-07-19 11:22 UTC, DzmitryYafremenka commented on task003/main.go
> +		if len(word) > len(maxWord) {
Input words1 := []string{"从", "too", "be", "or"}
Returns the result "从". This is 1 character. The correct result should be "too".

2021-07-19 11:22 UTC, DzmitryYafremenka commented on task003/main.go
> +	key1 := map[int]string{2: "a", 0: "b", 1: "c"}
If we try to add
`fmt.Println(key1)` right after this one the output will be:
```
map[0:b 1:c 2:a]
Map values sorted in order of increasing keys: [b c a]
```
same order as in sorted map.  So why do we need to sort map?
Assuming code is right - try to figure out why fmt.Println() outputs a sorted list and how to output an unsorted map.

p.s. no need to fix this code.

2021-07-19 22:12 UTC, karamel29 commented on task003/main.go
> +	key1 := map[int]string{2: "a", 0: "b", 1: "c"}
A map is an unordered collection of key-value pairs.
If you need a stable iteration order, you must maintain a separate data structure.

Also, starting with Go 1.12, the fmt package prints maps in key-sorted order to ease testing. So, this [article](https://habr.com/ru/post/457728/) says: "Причину можно найти в исходном коде рантайма языка:

```
// mapiterinit initializes the hiter struct used for ranging over maps. 
func mapiterinit(t *maptype, h *hmap, it *hiter) {...
// decide where to start 
r := uintptr(fastrand())
 ... 
it.startBucket = r & bucketMask(h.B)...}
```

Место поиска определяется рандомно, запомните это! Ходят слухи, что так разработчики рантайма заставляют пользователей не полагаться на порядок."

> How to output an unsorted map
Idk the answer, but judging by the information I found, no way. Or is there some way to do it?

2021-07-19 22:49 UTC, DzmitryYafremenka commented on task003/main.go
> +	key1 := map[int]string{2: "a", 0: "b", 1: "c"}
Yes, there is a way. All the randomness of the map is exposed when you iterate over it. Check out this Daft Punk song generator here as an example.
https://play.golang.org/p/7-vgnDpmd4b

2021-07-20 06:59 UTC, IgorZhadenovEpam approved these changes

2021-07-20 10:39 UTC, AliakseiM approved these changes

2021-07-20 10:39 UTC, AliakseiM commented on task003/main.go
> +	 if utf8.RuneCountInString(word) > utf8.RuneCountInString(maxWord) {
Nice!

2021-07-21 08:00 UTC, DzmitryYafremenka approved these changes

2021-07-22 05:38 UTC, merged