Lesson 04 task
karamel29/go-courses pull request #4
Opened 2021-07-25 17:39 UTC by karamel29

2021-07-26 07:41 UTC, DzmitryYafremenka requested changes

2021-07-26 07:41 UTC, DzmitryYafremenka commented on task004/main.go
> +type Circle struct {
Exported type should contain exportable fields or have a constructor. 
Currently, this type cannot be used outside the package.

https://play.golang.org/p/8OMazlGxikF

2021-07-27 10:06 UTC, DzmitryYafremenka approved these changes

2021-08-03 18:08 UTC, IgorZhadenovEpam approved these changes

2021-08-03 21:29 UTC, merged